### ISSUE TITLE
Timeline has no association named action

### ISSUE THREAD

**Issue by j0k3r** [sonata-project/SonataTimelineBundle#30]
It could be same issue like this one https://github.com/stephpy/timeline-bundle/issues/119 (which I got few times before).

I've installed the extend in my `Crm` namespace instead of `Application\Sonata`. Following install instruction from the [doc](http://sonata-project.org/bundles/timeline/master/doc/reference/installation.html).
I have multiple entity managers, so I switched to `auto_mapping: true` to be sure I didn't forgot any entities.

Mapping info says:

```
[OK]   FOS\UserBundle\Entity\Group
[OK]   FOS\UserBundle\Entity\User
[OK]   Sonata\UserBundle\Entity\BaseGroup
[OK]   Sonata\UserBundle\Entity\BaseUser
[OK]   Spy\TimelineBundle\Entity\Action
[OK]   Spy\TimelineBundle\Entity\Timeline
[OK]   Spy\TimelineBundle\Entity\Component
[OK]   Spy\TimelineBundle\Entity\ActionComponent
[OK]   Crm\UserBundle\Entity\Group
[OK]   Crm\UserBundle\Entity\User
[OK]   Crm\TimelineBundle\Entity\Action
[OK]   Crm\TimelineBundle\Entity\Timeline
[OK]   Crm\TimelineBundle\Entity\Component
[OK]   Crm\TimelineBundle\Entity\ActionComponent
```

Everything else is defined as the installation says. When I reach my dashboard, I got this error :

> An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 81 near 'a LEFT JOIN a.actionComponents': Error: Class Crm\TimelineBundle\Entity\Timeline has no association named action") in SonataAdminBundle:Core:dashboard.html.twig at line 49.

> [Semantical Error] line 0, col 81 near 'a LEFT JOIN a.actionComponents': Error: Class Crm\TimelineBundle\Entity\Timeline has no association named action

> SELECT t, a, ac, c FROM Crm\TimelineBundle\Entity\Timeline t INNER JOIN t.action a LEFT JOIN a.actionComponents ac LEFT JOIN ac.component c WHERE t.type = :type AND t.context = :context AND t.subject = :subject ORDER BY t.createdAt DESC

If I jump inside the `Crm\TimelineBundle\Entity\Timeline` file, I can see multiple BaseTimelime file until `Spy\Timeline\Model\Timeline` which seems to has the `action` field but not defined as a relation?

/ping @stephpy

**Comment by stephpy** [comment]
Please,

Can you exexute command `doctrine:schema:validate`. I never used timeline-bundle with many entity managers, it seems we have some issues with it. :\

**Comment by j0k3r** [comment]
Every thing seems to be ok:

```
$ php app/console doctrine:schema:validate
[Mapping]  OK - The mapping files are correct.
[Database] OK - The database schema is in sync with the mapping files.
```

**Comment by rande** [comment]
@j0k3r you need to configure the class configuration in ``sonata_timeline``.

**Comment by j0k3r** [comment]
@rande The same that are defined in `spy_timeline` ? (as I see in the [Configuration file](https://github.com/sonata-project/SonataTimelineBundle/blob/master/DependencyInjection/Configuration.php))

**Comment by rande** [comment]
Something, like this:

```yaml
sonata_timeline:
    manager_type: orm

    class:
        timeline:         %spy_timeline.class.timeline%
        action:           %spy_timeline.class.action%
        component:        %spy_timeline.class.component%
        actionComponent: %spy_timeline.class.action_component%
```

**Comment by rande** [comment]
I could make it more magical by settings the default to the parameter keys :/

**Comment by j0k3r** [comment]
Or at least put them in the documentation :)

**Comment by rande** [comment]
yep

**Comment by rande** [comment]
done: https://github.com/sonata-project/SonataTimelineBundle/commit/bf290b93b1356f1d7b34dc3ac4f6b8fe08ce6733

**Comment by j0k3r** [comment]
:+1: Thanks

**Comment by wbloszyk** [comment]
https://github.com/sonata-project/SonataTimelineBundle/issues/261#issuecomment-909441367

You should set classes in `sonata_timeline` too (with `user`):
```yaml
spy_timeline:
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                query_builder: ~ # Spy\TimelineBundle\Driver\ORM\QueryBuilder\QueryBuilder
                timeline:         App\Entity\SonataTimelineTimeline
                action:           App\Entity\SonataTimelineAction
                component:        App\Entity\SonataTimelineComponent
                action_component: App\Entity\SonataTimelineActionComponent

sonata_timeline:
    manager_type: orm
    class:
        user: App\Entity\SonataUserUser
        timeline: App\Entity\SonataTimelineTimeline
        action: App\Entity\SonataTimelineAction
        component: App\Entity\SonataTimelineComponent
        action_component: App\Entity\SonataTimelineActionComponent
```
